/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
import 'sst'
export {}
declare module 'sst' {
  export interface Resource {
    MyWeb: {
      type: 'sst.aws.Nextjs'
      url: string
    }
  }
}
